substitutions:
  name: m5stick-s3
  friendly_name: M5Stick S3
  idle_time: 30s
  pikud_flash_seconds: 3s
  pikud_safe_max_minutes_default: "5"

packages:
  m5stick_hardware: !include packages/m5stick_hardware.yaml
  m5stick_sensors: !include packages/m5stick_sensors.yaml
  m5stick_buttons: !include packages/m5stick_buttons.yaml
  m5stick_ui: !include packages/m5stick_ui.yaml
  m5stick_scripts: !include packages/m5stick_scripts.yaml
